'use client';
import {useEffect,useReducer,useRef,useState} from 'react';
import {ArrowLeft,Check,Copy,Mic,Pause,Play,Plus,Search,Settings,Square,Trash2,Pin,X,MoreHorizontal,Share2,Pencil,RotateCcw} from 'lucide-react';
import {complete,initialNotes,items,notesReducer,type Note} from './ascy-model';
import './ascy-prototype.css';
type View='home'|'detail'|'edit'|'discard'|'voice'|'delete'|'share'|'settings'|'reset';
type Phase='connecting'|'listening'|'paused'|'processing';
const samples=[{title:'Plan the weekend',body:'Book a table for Saturday\nPick up flowers\nCall mom',kind:'list' as const},{title:'A thought for later',body:'Make more room for the things that give you energy. Start with a long walk on Sunday.',kind:'note' as const},{title:'Pack for the trip',body:'Passport\nTickets\nCharger\nA book for the journey',kind:'list' as const}];
const blank=():Note=>({id:'',title:'',body:'',kind:'note',checked:[],pinned:false});
export function AscyPrototype(){
 const [notes,dispatch]=useReducer(notesReducer,initialNotes);
 const [view,setView]=useState<View>('home');const [selected,setSelected]=useState('groceries');
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const [menu,setMenu]=useState(false);
 const [draft,setDraft]=useState<Note>(blank);const [original,setOriginal]=useState('');const [error,setError]=useState('');
 const [phase,setPhase]=useState<Phase>('connecting');const [sample,setSample]=useState(0);const [voiceEdit,setVoiceEdit]=useState(false);
 const [toast,setToast]=useState('');const [deleted,setDeleted]=useState<Note|null>(null);const [motion,setMotion]=useState(true);const [feedback,setFeedback]=useState(true);
 const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);
 const frame=useRef<HTMLDivElement>(null);const shareText=useRef<HTMLTextAreaElement>(null);const sequence=useRef(0);
 const active=notes.find(n=>n.id===selected);
 const notify=(text:string)=>{if(feedback)setToast(text);};
 const go=(next:View)=>{setMenu(false);setError('');setView(next);};
 const open=(id:string)=>{setSelected(id);go('detail');};
 useEffect(()=>{frame.current?.querySelector<HTMLElement>('[data-focus]')?.focus({preventScroll:true});},[view]);
 useEffect(()=>{if(!toast||toast==='Note deleted')return;const timer=setTimeout(()=>setToast(''),6000);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{
  if(view!=='voice'||(phase!=='connecting'&&phase!=='processing'))return;
  const timer=setTimeout(()=>{
   if(phase==='connecting'){setPhase('listening');return;}
   const s=samples[sample];const existing=voiceEdit?notes.find(n=>n.id===selected):undefined;
   const note:Note=existing?{...existing,body:existing.body+'\n'+s.body}:{...blank(),...s,id:`voice-${++sequence.current}`};
   dispatch({type:'save',note});setSelected(note.id);setView('detail');if(feedback)setToast(existing?'Voice content added':'Your note is ready');
  },phase==='connecting'?650:1000);return()=>clearTimeout(timer);
 },[view,phase,sample,voiceEdit,notes,selected,feedback]);
 const startEdit=(note?:Note)=>{if(note)setSelected(note.id);const d=note?{...note,checked:[...note.checked]}:blank();setDraft(d);setOriginal(JSON.stringify(d));go('edit');};
 const cancelEdit=()=>{if(JSON.stringify(draft)!==original)go('discard');else go(draft.id?'detail':'home');};
 const save=()=>{if(!draft.title.trim()){setError('Give your note a title.');return;}if(!draft.body.trim()){setError('Add some content before saving.');return;}const clean={...draft,title:draft.title.trim(),body:draft.body.trim(),id:draft.id||`manual-${++sequence.current}`,checked:draft.checked.filter(i=>draft.body.split('\n').map(s=>s.trim()).includes(i))};dispatch({type:'save',note:clean});setSelected(clean.id);go('detail');notify('Note saved');};
 const voice=(edit=false)=>{setVoiceEdit(edit);setPhase('connecting');setSample(0);go('voice');};
 const cancelVoice=()=>go(voiceEdit&&active?'detail':'home');
 const back=()=>{if(view==='edit')cancelEdit();else if(view==='voice')cancelVoice();else if(['delete','share'].includes(view))go('detail');else if(view==='discard')go('edit');else if(view==='reset')go('settings');else go('home');};
 const text=active?active.title+'\n\n'+active.body:'';
 const copy=async()=>{try{if(!navigator.clipboard)throw new Error('Unavailable');await navigator.clipboard.writeText(text);setCopied(true);setCopyError(false);}catch{setCopyError(true);shareText.current?.focus();shareText.current?.select();}};
 const visible=notes.filter(n=>(filter!=='Pinned'||n.pinned)&&(filter!=='Completed'||complete(n))&&(n.title+' '+n.body).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.pinned)-Number(a.pinned));
 const title=view==='home'?'My Notes':view==='settings'?'Settings':view==='edit'?(draft.id?'Edit note':'New note'):view==='voice'?'Voice capture':view==='share'?'Share note':view==='delete'?'Delete note?':view==='discard'?'Discard changes?':view==='reset'?'Reset demo?':active?.title||'My Notes';
 return <div className="ap-experience" id="voice-walkthrough">
 <div className="ap-introduction"><span className="as-kicker">02 / TRY THE EXPERIENCE</span><h2>Your thoughts.<br/><i>In your hands.</i></h2><p>Create a note, check off a list, or try a voice capture. Everything happens right here.</p><div className="ap-scenarios"><span>THREE PLACES TO START</span><button disabled={view!=='home'} onClick={()=>{go('home');setQuery('');setFilter('All');}}>01 <b>Explore your notes</b><span>Find, pin, edit, and complete.</span></button><button disabled={view!=='home'} onClick={()=>voice()}>02 <b>Capture a thought</b><span>Try the guided voice sequence.</span></button><button disabled={view!=='home'} onClick={()=>startEdit()}>03 <b>Make it your own</b><span>Write and save a real note.</span></button></div><p className="ap-disclaimer">Interactive demo. Voice uses sample recordings; your microphone stays off. Notes live in this preview until the page reloads.</p></div>
 <div className="ap-stage"><div className={`ap-device ${motion?'':'ap-no-motion'}`} ref={frame} onKeyDown={e=>{if(e.key==='Escape'&&view!=='home'){e.preventDefault();back();}}} aria-label="Ascy interactive prototype">
 <div className="ap-status" aria-hidden="true"><span>9:41</span><span>••• ▰</span></div>
 <header className="ap-header">{view!=='home'?<button aria-label="Back" onClick={back}><ArrowLeft size={20}/></button>:<span className="ap-brand">ascy</span>}<span className="ap-header-label">{view==='home'?'YOUR DAILY SPACE':'YOUR THOUGHTS, ORGANISED'}</span>{view==='home'?<button aria-label="Settings" onClick={()=>go('settings')}><Settings size={20}/></button>:<button aria-label="Close to notes" onClick={()=>{if(view==='edit')cancelEdit();else if(view==='discard')go('edit');else if(view==='voice')cancelVoice();else go('home');}}><X size={19}/></button>}</header>
 <div className="ap-content" key={view}><h3 tabIndex={-1} data-focus className="ap-title">{title}</h3>
 {view==='home'&&<><div className="ap-search"><Search size={17}/><input aria-label="Search notes" placeholder="Search your notes" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={16}/></button>}</div><div className="ap-filters" aria-label="Note filters">{['All','Pinned','Completed'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><p className="ap-list-label">{query?'SEARCH RESULTS':filter.toUpperCase()+' NOTES'} · {visible.length}</p><div className="ap-notes">{visible.map(n=><article key={n.id} className="ap-card"><button className="ap-card-open" onClick={()=>open(n.id)}><span>{n.pinned&&<Pin size={12}/>} {n.title}</span><small>{n.kind==='list'?`${n.checked.filter(i=>items(n).includes(i)).length}/${items(n).length} complete`:n.body.slice(0,64)}</small><em>{n.kind==='list'?'CHECKLIST':'NOTE'} {complete(n)&&'· COMPLETED'}</em></button><button aria-label={`Edit ${n.title}`} onClick={()=>startEdit(n)}><Pencil size={15}/></button></article>)}</div>{!visible.length&&<div className="ap-empty"><Search size={28}/><h4>{query?'No matches yet':filter==='Pinned'?'Keep a favourite close':filter==='Completed'?'One thing at a time':'A little space for your thoughts'}</h4><p>{query?'Try another word, or clear your search.':filter==='Pinned'?'Open a note and pin it from the actions menu.':filter==='Completed'?'Finish a checklist and it will appear here.':'Create a note or try voice capture to get started.'}</p>{query?<button className="ap-primary" onClick={()=>setQuery('')}>Clear search</button>:filter!=='All'?<button className="ap-primary" onClick={()=>setFilter('All')}>See all notes</button>:<button className="ap-primary" onClick={()=>startEdit()}>Create a note</button>}</div>}</>}
 {view==='detail'&&active&&<><div className="ap-detail-meta">{active.kind==='list'?'CHECKLIST':'NOTE'}{active.pinned?' · PINNED':''}</div><div className="ap-tools"><button onClick={()=>startEdit(active)}><Pencil size={16}/>Edit</button><button onClick={()=>{setCopied(false);setCopyError(false);go('share');}}><Share2 size={16}/>Share</button><button aria-label="More note actions" aria-expanded={menu} onClick={()=>setMenu(!menu)}><MoreHorizontal size={22}/></button></div>{menu&&<div className="ap-menu"><button onClick={()=>{dispatch({type:'pin',id:active.id});setMenu(false);notify(active.pinned?'Note unpinned':'Pinned to the top');}}><Pin size={16}/>{active.pinned?'Unpin':'Pin to top'}</button><button onClick={()=>voice(true)}><Mic size={16}/>Add by voice</button><button className="ap-danger" onClick={()=>go('delete')}><Trash2 size={16}/>Delete note</button></div>}{active.kind==='list'?<div className="ap-checklist">{items(active).map((item,i)=><label key={i}><input type="checkbox" checked={active.checked.includes(item)} onChange={()=>dispatch({type:'check',id:active.id,item})}/><span>{item}</span></label>)}<button className="ap-secondary" onClick={()=>dispatch({type:'complete',id:active.id})}>{complete(active)?'Mark all incomplete':'Complete all items'}</button>{complete(active)&&<p className="ap-success"><Check size={16}/>All done. A little more headspace.</p>}</div>:<p className="ap-note-body">{active.body}</p>}<button className="ap-secondary ap-detail-return" onClick={()=>go('home')}>Back to My Notes</button></>}
 {view==='edit'&&<form onSubmit={e=>{e.preventDefault();save();}} className="ap-editor"><label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} maxLength={100} placeholder="Give your thought a name" aria-invalid={!!error&&!draft.title.trim()}/></label><fieldset><legend>Format</legend>{(['note','list'] as const).map(kind=><label key={kind}><input type="radio" name="ascy-format" checked={draft.kind===kind} onChange={()=>setDraft({...draft,kind})}/>{kind==='note'?'Note':'Checklist'}</label>)}</fieldset><label>{draft.kind==='list'?'Items · one per line':'Your note'}<textarea value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} placeholder={draft.kind==='list'?'Milk\nBread\nSomething for dinner':'What’s on your mind?'} rows={7}/></label>{error&&<p role="alert" className="ap-error">{error}</p>}<button className="ap-primary" type="submit"><Check size={17}/>Save note</button><button className="ap-secondary" type="button" onClick={cancelEdit}>Cancel</button></form>}
 {view==='voice'&&<div className={`ap-voice ap-${phase}`}><div className="ap-orb-window" aria-hidden="true"><img src="/images/ascy/listening.png" alt=""/></div><h4 aria-live="polite">{phase==='connecting'?'Getting ready…':phase==='processing'?'Making a little sense of it…':phase==='paused'?'Take your time.':'Listening…'}</h4><p>{phase==='paused'?'Resume whenever you’re ready.':phase==='processing'?'Turning your sample into a note.':voiceEdit?'Add a little more to your note.':'A sample thought, ready to capture.'}</p>{(phase==='listening'||phase==='paused')&&<><label className="ap-sample">Sample thought<select value={sample} onChange={e=>setSample(Number(e.target.value))}>{samples.map((s,i)=><option value={i} key={s.title}>{s.title}</option>)}</select></label><blockquote>{samples[sample].body.replaceAll('\n',', ')}</blockquote><div className="ap-record-controls"><button onClick={()=>setPhase(phase==='paused'?'listening':'paused')}>{phase==='paused'?<Play size={19}/>:<Pause size={19}/>} {phase==='paused'?'Resume':'Pause'}</button><button className="ap-stop" onClick={()=>setPhase('processing')}><Square size={16}/>Finish</button></div></>}<button className="ap-secondary" onClick={cancelVoice}>Cancel recording</button></div>}
 {view==='delete'&&active&&<div className="ap-confirm"><Trash2 size={30}/><p>“{active.title}” will be removed. You can undo this after deleting.</p><button className="ap-destructive" onClick={()=>{setDeleted(active);dispatch({type:'delete',id:active.id});go('home');setToast('Note deleted');}}>Delete note</button><button className="ap-secondary" onClick={()=>go('detail')}>Keep note</button></div>}
 {view==='discard'&&<div className="ap-confirm"><p>Your changes haven’t been saved. Keep editing, or leave this draft behind.</p><button className="ap-primary" onClick={()=>go('edit')}>Keep editing</button><button className="ap-secondary" onClick={()=>go(draft.id?'detail':'home')}>Discard changes</button></div>}
 {view==='share'&&<div className="ap-share"><p>Copy your note to share it in a message or another app.</p><textarea aria-label="Note text to copy" value={text} readOnly rows={8} ref={shareText}/><button className="ap-primary" onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'Copied':'Copy note'}</button>{copied&&<p className="ap-success" role="status">Ready to paste wherever you need it.</p>}{copyError&&<p role="status">Automatic copy isn’t available here. The text is selected—use your device’s Copy command.</p>}<button className="ap-secondary" onClick={()=>go('detail')}>Done</button></div>}
 {view==='settings'&&<div className="ap-settings"><p>Make this space feel like yours.</p><label><span>Interface motion<small>Gentle transitions and recording feedback</small></span><input type="checkbox" checked={motion} onChange={e=>setMotion(e.target.checked)}/></label><label><span>Action confirmations<small>Show a message when a note is saved or pinned</small></span><input type="checkbox" checked={feedback} onChange={e=>setFeedback(e.target.checked)}/></label><div className="ap-settings-info">Voice preview<small>Sample content · No microphone access</small></div><button className="ap-secondary" onClick={()=>go('reset')}><RotateCcw size={16}/>Reset demo notes</button><button className="ap-primary" onClick={()=>go('home')}>Done</button></div>}
 {view==='reset'&&<div className="ap-confirm"><p>This clears your demo changes and restores the three sample notes.</p><button className="ap-destructive" onClick={()=>{dispatch({type:'reset'});setDeleted(null);setFilter('All');setQuery('');setSelected('groceries');setToast('Demo reset');go('home');}}>Reset demo</button><button className="ap-secondary" onClick={()=>go('settings')}>Keep my notes</button></div>}
 </div>
 {view==='home'&&<footer className="ap-dock"><button className="ap-new" onClick={()=>startEdit()}><Plus size={18}/>New note</button><button className="ap-mic" aria-label="Create a note by voice" onClick={()=>voice()}><Mic size={22}/></button></footer>}
 {toast&&<div className="ap-toast" role="status"><span>{toast}</span>{toast==='Note deleted'&&deleted&&<button onClick={()=>{dispatch({type:'restore',note:deleted});setSelected(deleted.id);setDeleted(null);setToast('Note restored');go('detail');}}>Undo</button>}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={15}/></button></div>}
 <div className="ap-home-indicator" aria-hidden="true"/>
 </div><span className="ap-stage-note">BUILT TO BE EXPLORED · NO EXTERNAL LINKS</span></div>
 </div>;
}
