'use client';
import {useState} from 'react';
import {ArrowLeft, ArrowRight, Check, RotateCcw, Eye, EyeOff} from 'lucide-react';
import './lumio-demo.css';

export function LumioDemo(){
 const [step,setStep]=useState(0);const [bank,setBank]=useState('');const [connected,setConnected]=useState(false);const [email,setEmail]=useState('');const [invited,setInvited]=useState(false);const [hidden,setHidden]=useState(false);const [notice,setNotice]=useState('');
 const titles=['A little more together.','Choose your bank','Your accounts, your choice','Invite your partner','Your shared space'];
 function reset(){setStep(0);setBank('');setConnected(false);setEmail('');setInvited(false);setHidden(false);setNotice('');}
 return <section className="lumio-demo" id="lumio-prototype" aria-labelledby="lumio-demo-title"><div className="ld-context"><span className="eyebrow">INTERACTIVE PRODUCT WALKTHROUGH</span><h2 id="lumio-demo-title">The first shared moment.</h2><p>Explore getting started, connecting a sample account, inviting a partner, and controlling what you share.</p><img src="/images/lumio-phones.png" alt="Original Lumio shared spending interface designs" width="1080" height="1416" loading="lazy"/><p className="ld-disclaimer">Reconstructed portfolio demo based on the case study. Fictional balances and transactions; no banking connection or invitation is sent.</p></div><div className="ld-phone"><header><strong>lumio</strong><button onClick={reset} aria-label="Restart Lumio demo" title="Restart demo"><RotateCcw size={18}/></button></header><div className="ld-progress" aria-label={`Step ${step+1} of 5`}>{titles.map((t,i)=><span key={t} className={i<=step?'done':''}/>)}</div><div className="ld-screen" key={step}><div className="ld-back">{step>0&&<button onClick={()=>{setStep(step-1);setNotice('');}} aria-label="Previous step" title="Previous step"><ArrowLeft size={18}/></button>}<small>{step+1} / 5</small></div><h3>{titles[step]}</h3>
 {step===0&&<><p>See shared spending in one place, while keeping your own account and independence.</p><ul><li>Understand your combined spending</li><li>Keep personal purchases private</li><li>Plan upcoming payments together</li></ul><button className="ld-primary" onClick={()=>setStep(1)}>Get started <ArrowRight size={18}/></button></>}
 {step===1&&<><p>Select a sample bank. You can explore without connecting one.</p><fieldset><legend>Bank</legend>{['Monzo','Barclays','Starling'].map(b=><label className="ld-choice" key={b}><input type="radio" name="bank" value={b} checked={bank===b} onChange={()=>setBank(b)}/>{b}{bank===b&&<Check size={16}/>}</label>)}</fieldset><button className="ld-primary" disabled={!bank} onClick={()=>setStep(2)}>Continue <ArrowRight size={18}/></button><button className="ld-text" onClick={()=>{setConnected(false);setStep(3);}}>Explore without a bank</button></>}
 {step===2&&<><p>{bank} · Sample current account ending 2048</p><div className="ld-balance"><small>Available balance</small><strong>£2,450.00</strong></div><p>You choose which transactions to share. This preview does not request banking credentials.</p><button className="ld-primary" onClick={()=>{setConnected(true);setStep(3);}}>Use sample account <Check size={18}/></button><button className="ld-text" onClick={()=>setStep(1)}>Choose a different bank</button></>}
 {step===3&&<form onSubmit={e=>{e.preventDefault();setInvited(true);setStep(4);}}><p>Bring your partner into your shared space. You can also do this later.</p><label>Partner email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="partner@example.com"/></label><button className="ld-primary">Preview invitation <ArrowRight size={18}/></button><button className="ld-text" type="button" onClick={()=>setStep(4)}>I'll do this later</button></form>}
 {step===4&&<><p role="status">{invited?'Invitation preview ready.':'Your space is ready to explore.'} {connected?`${bank} sample account added.`:'Showing sample data.'}</p><div className="ld-balance"><small>Shared spending this month</small><strong>£{hidden?'1,240':'1,285'}.00</strong></div><div className="ld-transaction"><span>Groceries<small>Shared · £86.00</small></span><Check size={18}/></div><div className="ld-transaction"><span>Gift purchase<small>{hidden?'Private · excluded from shared total':'Shared · £45.00'}</small></span><button onClick={()=>{setHidden(!hidden);setNotice(hidden?'Gift purchase is shared.':'Gift purchase is now private.');}} aria-label={hidden?'Share gift purchase':'Hide gift purchase'} title={hidden?'Share transaction':'Make private'}>{hidden?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><p className="ld-notice" role="status">{notice}</p><button className="ld-primary" onClick={()=>setStep(invited?1:3)}>{invited?'Manage accounts':'Invite your partner'} <ArrowRight size={18}/></button><button className="ld-text" onClick={reset}>Explore again</button></>}
 </div></div></section>;
}
