'use client';
import {useState, useEffect} from 'react';
import {Home, CalendarDays, Wallet, Users, Settings, Check, Eye, EyeOff, ArrowRight, ChevronDown, Plus, Trash2} from 'lucide-react';
import './lumio-workspace.css';

type Props={bank:string;connected:boolean;email:string;invited:boolean;hidden:boolean;onPrivacy:()=>void;onConnect:()=>void;onDisconnect:()=>void;onInvite:(email:string)=>void};
const money=(value:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(value);
const tabs=[{id:'home',name:'Overview',icon:Home},{id:'payments',name:'Payments',icon:CalendarDays},{id:'accounts',name:'Accounts',icon:Wallet},{id:'partner',name:'Partner',icon:Users},{id:'settings',name:'Settings',icon:Settings}] as const;

function Panel({title,children,open=false}:{title:string;children:React.ReactNode;open?:boolean}){return <details className="lw-panel" open={open||undefined}><summary>{title}<ChevronDown size={17}/></summary><div className="lw-panel-content">{children}</div></details>;}

export function LumioWorkspace(p:Props){
 const [tab,setTab]=useState<string>('home');const [notice,setNotice]=useState('');const [month,setMonth]=useState('September');const [partnerEmail,setPartnerEmail]=useState(p.email);const [inviteStatus,setInviteStatus]=useState(p.invited?'pending':'none');const [notifications,setNotifications]=useState(true);const [budget,setBudget]=useState(1600);const [editingBudget,setEditingBudget]=useState(false);const [draftBudget,setDraftBudget]=useState('1600');const [addPayment,setAddPayment]=useState(false);const [paymentName,setPaymentName]=useState('');const [paymentAmount,setPaymentAmount]=useState('');const [paymentDate,setPaymentDate]=useState('2026-09-25');const [confirmDisconnect,setConfirmDisconnect]=useState(false);
 const [payments,setPayments]=useState([{id:1,name:'Rent',amount:950,date:'2026-09-28',paid:false},{id:2,name:'Internet',amount:32,date:'2026-09-30',paid:false}]);
 useEffect(()=>{setPartnerEmail(p.email);setInviteStatus(p.invited?'pending':'none');},[p.email,p.invited]);
 const total=month==='September'?(p.hidden?1240:1285):1178;
 function navigate(id:string){setTab(id);setNotice('');}
 return <div className="lw-app"><div className="lw-view" key={tab}><h3>{tabs.find(t=>t.id===tab)?.name}</h3>
 {tab==='home'&&<><div className="lw-month"><label htmlFor="lw-month">Shared spending</label><select id="lw-month" value={month} onChange={e=>setMonth(e.target.value)}><option>September</option><option>August</option></select></div><div className="lw-total" key={total}>{money(total)}</div><button className="lw-budget" onClick={()=>setEditingBudget(!editingBudget)} aria-expanded={editingBudget}><span>{money(Math.abs(budget-total))} {total<=budget?'left of':'over'} {money(budget)} budget</span><ChevronDown size={16}/></button><div className="lw-meter" role="meter" aria-label="Monthly budget used" aria-valuemin={0} aria-valuemax={budget} aria-valuenow={Math.min(total,budget)}><span style={{width:`${Math.min(100,total/budget*100)}%`}}/></div>{editingBudget&&<form className="lw-form" onSubmit={e=>{e.preventDefault();setBudget(Number(draftBudget));setEditingBudget(false);setNotice('Monthly budget updated.');}}><label>Monthly budget (£)<input type="number" min="1" max="100000" required value={draftBudget} onChange={e=>setDraftBudget(e.target.value)}/></label><button className="ld-primary">Save budget <Check size={16}/></button></form>}
 <Panel title="Spending breakdown" open><div className="lw-category"><span>Home & bills</span><strong>{money(month==='September'?950:900)}</strong></div><div className="lw-category"><span>Food & everyday</span><strong>{money(month==='September'?290:278)}</strong></div>{month==='September'&&!p.hidden&&<div className="lw-category"><span>Gifts</span><strong>£45.00</strong></div>}</Panel>
 <Panel title="Transactions" open><details className="lw-transaction"><summary><span>Groceries<small>Everyday spending</small></span><strong>£86.00</strong><ChevronDown size={15}/></summary><div><p>Sample current account · 8 {month} 2026</p><p>Shared with your partner. Included in Food & everyday.</p></div></details>{month==='September'&&<details className="lw-transaction"><summary><span>Gift purchase<small>{p.hidden?'Private':'Shared'}</small></span><strong>£45.00</strong><ChevronDown size={15}/></summary><div><p>Sample current account · 6 September 2026</p><p>{p.hidden?'Only you can see this purchase. It is excluded from shared spending.':'This purchase appears in your shared spending.'}</p><button className="lw-action" onClick={()=>{p.onPrivacy();setNotice(p.hidden?'Gift purchase shared.':'Gift purchase is now private.');}}>{p.hidden?<Eye size={16}/>:<EyeOff size={16}/>} {p.hidden?'Share gift purchase':'Hide gift purchase'}</button></div></details>}</Panel><button className="lw-action" onClick={()=>navigate('payments')}>Upcoming payments <ArrowRight size={16}/></button></>}
 {tab==='payments'&&<><p>Plan what is coming next.</p><div className="lw-total">{money(payments.filter(x=>!x.paid).reduce((sum,x)=>sum+x.amount,0))}<small>Upcoming total</small></div>{payments.length===0&&<p>No payments scheduled. Add your next shared bill.</p>}{payments.map(item=><details className="lw-transaction" key={item.id}><summary><span>{item.name}<small>{item.paid?'Marked paid':new Date(item.date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</small></span><strong>{money(item.amount)}</strong><ChevronDown size={15}/></summary><div><p>{item.paid?'This sample payment is complete.':'Planned shared expense. No money will be moved.'}</p><button className="lw-action" onClick={()=>{setPayments(v=>v.map(x=>x.id===item.id?{...x,paid:!x.paid}:x));setNotice(item.paid?'Payment moved to upcoming.':'Payment marked paid.');}}><Check size={16}/>{item.paid?'Mark upcoming':'Mark paid'}</button><button className="lw-action" onClick={()=>{setPayments(v=>v.filter(x=>x.id!==item.id));setNotice(`${item.name} removed from this demo.`);}}><Trash2 size={16}/>Remove payment</button></div></details>)}<button className="lw-action" onClick={()=>setAddPayment(!addPayment)} aria-expanded={addPayment}><Plus size={16}/>{addPayment?'Cancel new payment':'Add payment'}</button>{addPayment&&<form className="lw-form" onSubmit={e=>{e.preventDefault();setPayments(v=>[...v,{id:Date.now(),name:paymentName.trim(),amount:Number(paymentAmount),date:paymentDate,paid:false}]);setAddPayment(false);setPaymentName('');setPaymentAmount('');setNotice('Payment added to your plan.');}}><label>Payment name<input required maxLength={50} pattern=".*\S.*" value={paymentName} onChange={e=>setPaymentName(e.target.value)}/></label><label>Amount (£)<input required type="number" min="0.01" max="100000" step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/></label><label>Due date<input required type="date" value={paymentDate} onChange={e=>setPaymentDate(e.target.value)}/></label><button className="ld-primary">Save payment <Check size={16}/></button></form>}</>}
 {tab==='accounts'&&<><p>Your accounts remain yours. You decide what to share.</p>{p.connected?<Panel title={`${p.bank} · Current account`} open><div className="lw-total">£2,450.00<small>Sample balance · ending 2048</small></div><p>Balance and transaction data are fictional.</p><button className="lw-action" onClick={()=>setConfirmDisconnect(!confirmDisconnect)} aria-expanded={confirmDisconnect}>Disconnect account</button>{confirmDisconnect&&<div className="lw-confirm"><p>Remove this sample connection? You can reconnect at any time.</p><button className="lw-action" onClick={()=>{p.onDisconnect();setConfirmDisconnect(false);setNotice('Sample account disconnected.');}}>Confirm disconnect</button><button className="lw-action" onClick={()=>setConfirmDisconnect(false)}>Keep account</button></div>}</Panel>:<p className="lw-empty">No bank connected. Your sample shared space is still available.</p>}<button className="ld-primary" onClick={p.onConnect}>{p.connected?'Change sample bank':'Connect sample bank'}<Plus size={16}/></button><Panel title="What gets shared?"><p>Individual banking credentials are never shared. In this demo, you can make the gift transaction private from Overview.</p><button className="lw-action" onClick={()=>navigate('home')}>Manage shared spending <ArrowRight size={16}/></button></Panel></>}
 {tab==='partner'&&<><p>One shared space. Two independent people.</p>{inviteStatus==='none'?<form className="lw-form" onSubmit={e=>{e.preventDefault();p.onInvite(partnerEmail);setInviteStatus('pending');setNotice('Invitation preview created. Nothing was sent.');}}><label>Partner email<input required type="email" value={partnerEmail} onChange={e=>setPartnerEmail(e.target.value)} placeholder="partner@example.com"/></label><button className="ld-primary">Preview invitation <ArrowRight size={16}/></button></form>:<Panel title={inviteStatus==='pending'?'Invitation pending':'Partner connected'} open><p className="lw-email">{partnerEmail}</p><p>{inviteStatus==='pending'?'This is a local invitation preview.':'Your sample partner can now see shared spending, excluding private purchases.'}</p>{inviteStatus==='pending'&&<button className="ld-primary" onClick={()=>{setInviteStatus('accepted');setNotice('Sample partner joined your space.');}}>Preview partner joining <Check size={16}/></button>}<button className="lw-action" onClick={()=>{setInviteStatus('none');setNotice('Invitation reset. You can invite someone else.');}}>{inviteStatus==='pending'?'Cancel invitation':'Reset sample partner'}</button></Panel>}<Panel title="Sharing preferences"><p>Each person keeps control of their transactions. Private purchases are excluded from the shared view.</p><button className="lw-action" onClick={()=>navigate('home')}>Review your transactions <ArrowRight size={16}/></button></Panel></>}
 {tab==='settings'&&<><Panel title="Notifications" open><label className="lw-switch"><span>Upcoming payment reminders</span><input type="checkbox" role="switch" checked={notifications} onChange={e=>{setNotifications(e.target.checked);setNotice(e.target.checked?'Reminders enabled in this demo.':'Reminders disabled.');}}/></label></Panel><Panel title="Privacy & demo data"><p>All balances, payments, and activity are sample data held only for this session. No credentials, requests, or payments are sent.</p><button className="lw-action" onClick={()=>navigate('accounts')}>Manage accounts <ArrowRight size={16}/></button></Panel><Panel title="Help"><p>Expand a transaction to control its visibility. Expand a payment to mark it paid or remove it. The restart control clears this demo.</p><button className="lw-action" onClick={()=>navigate('home')}>Return to overview <Home size={16}/></button></Panel></>}
 </div><p role="status" className="lw-status" key={notice}>{notice}</p><nav className="lw-tabs" aria-label="Lumio app navigation">{tabs.map(({id,name,icon:Icon})=><button key={id} onClick={()=>navigate(id)} aria-current={tab===id?'page':undefined} title={name}><Icon size={19}/><span>{name}</span></button>)}</nav></div>;
}
