import {ArrowUpRight,ArrowDown,ArrowRight,ChevronDown} from 'lucide-react';
import cases from './data.json';
import {originalPages} from './notion-article';
import {CaseHeader,CaseFooter} from './components';
import {LumioDemo} from './lumio-demo';
import {LumioEditorialMotion} from './lumio-editorial-motion';
import './lumio-editorial.css';

const series=[['lumio-couples','Couples Spending'],['lumio-activation','Activation'],['lumio-design-system','Design System'],['lumio-visual-redesign','Visual Redesign']];
const screens=['/notion/cfad2053-bd8b-4d58-88cf-f34790f44b32.webp','/notion/36cf6baa-a432-4f2d-94d2-88914851b4e8.webp','/notion/ed953546-0d85-4adc-b060-e0e3d9d43c42.webp'];
const config:Record<string,{label:string;headline:string;statement:string;focus:string;images:string[];captions:string[];facts:string[][]}>={
 'lumio-couples':{label:'PRODUCT STRATEGY / RESEARCH / MOBILE',headline:'Together, on your terms.',statement:'Shared money should not mean giving up independence.',focus:'A shared view. Individual control.',images:screens,captions:['A shared space, with contributions and upcoming costs in view.','A clearer picture of recurring commitments.','Control lives at the transaction level.'],facts:[['32','Interviews completed'],['7','Macro jobs to be done'],['200+','Screens delivered'],['14+','Microprototypes']]},
 'lumio-activation':{label:'PRODUCT GROWTH / ONBOARDING / EXPERIMENTATION',headline:'Less setup. More possibility.',statement:'Let people experience the value before asking them to do the work.',focus:'From registration to a first shared moment.',images:['/notion/c25f4304-6e89-4e3e-be0f-1dc0696e3223.webp','/notion/5b97fc7c-c5ed-4330-9d68-ad096682a7f6.png','/notion/0f9cdb1c-adf1-4d49-a59d-9c74bdd75350.webp'],captions:['The original entry experience and choice of financial goals.','Exploring a faster path into shared value.','High-fidelity flows and delivery annotations.'],facts:[['19 → 44%','Partner invitations'],['55 → 71%','Bank connections'],['4 → 2','Flow options shortlisted'],['30 days','Reported experiment']]},
 'lumio-design-system':{label:'DESIGN SYSTEMS / TOKENS / BRAND FOUNDATIONS',headline:'One language. Every detail.',statement:'Consistency is not a finishing touch. It is a way to move.',focus:'A foundation that works at product speed.',images:['/notion/596f07ae-6ec6-47b8-b568-d030c5a5d5e6.png','/notion/3a6ef88b-e544-45c4-bf87-5ce838619e68.png','/notion/c9eb214c-fabc-4cfd-914a-e5cabd2f4dd0.png'],captions:['Semantic color tokens organize the light-theme foundations.','Shared component states bring the system into everyday product work.','Categories and icon treatments support repeatable financial patterns.'],facts:[['Tokens','Semantic foundations'],['Light / dark','Theme foundations'],['Atomic','Component approach'],['Product','Built for real flows']]},
 'lumio-visual-redesign':{label:'VISUAL DIRECTION / PRODUCT IDENTITY / MOBILE',headline:'Everyday money, reimagined.',statement:'A new product direction needs a visual language that belongs to it.',focus:'From financial information to a shared experience.',images:['/notion/7a986528-dc28-4b87-915a-4c41595377da.webp','/notion/2ddf4ff7-6206-4cc7-970b-158754df5509.webp'],captions:['Original product presentation: shared spaces, recurring costs, and goals.','Additional interface imagery retained in the original case archive.'],facts:[['Identity','Product expression'],['Mobile','Interface design'],['System','Reusable foundations'],['2022 →','Lumio engagement']]},
};

export function LumioEditorial({slug}:{slug:string}){const data=cases.find(c=>c.slug===slug);const design=config[slug];if(!data||!design)return null;const interactive=['lumio-couples','lumio-activation'].includes(slug);const index=series.findIndex(([id])=>id===slug);const next=series[(index+1)%series.length];const original=originalPages[slug];let archive=original?.html||'';const videoStart=archive.indexOf('<div class="notion-columns"><div class="notion-column"><figure class="notion-video"');const videoEnd=archive.indexOf('<h2 id="n-f68e19be-d1f5-4abb-a70d-f3fab0061d9e">',videoStart);if(slug==='lumio-couples'&&videoStart>=0&&videoEnd>videoStart)archive=archive.slice(0,videoStart)+archive.slice(videoEnd);const narrative=data.sections.filter(s=>s.title!=='Private walkthrough');
 return <><CaseHeader/><LumioEditorialMotion><main id="main"><section className={`le-hero le-hero-${slug}`}><div className="le-shell le-hero-top"><a href="/cases">All cases <ArrowUpRight size={14}/></a><span>{design.label}</span><span>0{index+1} / LUMIO SERIES</span></div><div className="le-hero-copy"><h1>lumio<span>.</span></h1><p>{design.headline}</p><a href="#le-story">{series[index][1]} <ArrowDown size={16}/></a></div><div className={`le-hero-media ${interactive?'le-phones':'le-board'}`} aria-hidden="true">{interactive?screens.map((src,i)=><img key={src} src={src} alt="" width="400" height="840" className={`le-phone-${i}`} fetchPriority={i===1?'high':'auto'}/>):<img src={design.images[0]} alt="" width="1800" height="1100" fetchPriority="high"/>}</div></section>
 <nav className="le-series" aria-label="Lumio case studies"><div className="le-shell">{series.map(([id,label])=><a href={`/cases/${id}`} key={id} aria-current={id===slug?'page':undefined}>{label}</a>)}</div></nav>
 <section className="le-shell le-overview le-reveal" id="le-story"><div className="le-label">THE BRIEF</div><div className="le-overview-grid"><h2>{data.title}</h2><div><p className="le-lead">{data.summary}</p><dl className="le-metadata"><div><dt>My role</dt><dd>{data.role}</dd></div><div><dt>Scope</dt><dd>{series[index][1]}</dd></div><div><dt>Timeline</dt><dd>From 2022</dd></div><div><dt>Platform</dt><dd>Fintech · Mobile product</dd></div></dl>{interactive?<a className="le-link" href="#lumio-prototype">Explore the interactive product <ArrowUpRight size={18}/></a>:<a className="le-link" href="/cases/lumio-couples#lumio-prototype">See the system in use <ArrowUpRight size={18}/></a>}</div></div></section>
 <section className="le-facts-band"><div className="le-shell le-facts le-reveal">{design.facts.map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>{slug==='lumio-activation'&&<p className="le-shell le-evidence-note">Reported 30-day Variant A results. Sample sizes, complete control data, and statistical significance were not supplied.</p>}</section>
 <section className="le-statement"><div className="le-shell le-reveal"><span className="le-label">THE DESIGN QUESTION</span><h2>{design.statement}</h2><span className="le-statement-footer">INDEPENDENT ACCOUNTS. SHARED AMBITION.</span></div></section>
 <section className="le-shell le-narrative" aria-label="Design process">{narrative.map((section,i)=><div className="le-chapter le-reveal" key={section.title}><span className="le-label">0{i+1} / {i===0?'CONTEXT':i===narrative.length-1?'REFLECTION':'DESIGN DECISIONS'}</span><div className="le-chapter-grid"><h2>{section.title}</h2><div>{section.body.map((p,j)=><p key={j}>{p}</p>)}</div></div>{i===Math.min(1,narrative.length-1)&&<figure className="le-wide-art"><a href={design.images[0]} target="_blank" rel="noreferrer" aria-label="Open original design image at full size"><img src={design.images[0]} alt={design.captions[0]} loading="lazy"/></a><figcaption><span>ORIGINAL DESIGN MATERIAL</span>{design.captions[0]}<ArrowUpRight size={16}/></figcaption></figure>}</div>)}</section>
 <section className={`le-product-band ${interactive?'':'le-product-system'}`}><div className="le-shell"><div className="le-section-top le-reveal"><span className="le-label">CRAFT / IN CONTEXT</span><h2>{design.focus}</h2></div><div className={`le-product-gallery ${interactive?'le-gallery-phones':''}`}>{design.images.slice(interactive?0:1).map((src,i)=><figure className="le-reveal" key={src}><a href={src} target="_blank" rel="noreferrer" aria-label={`Open design reference ${i+1}`}><img src={src} alt={design.captions[interactive?i:i+1]} loading="lazy"/></a><figcaption><span>0{i+1}</span>{design.captions[interactive?i:i+1]}</figcaption></figure>)}</div></div></section>
 {interactive&&<section className="le-shell le-demo-section"><div className="le-section-top"><span className="le-label">EXPERIENCE THE PRODUCT</span><h2>From design decisions<br/>to something you can use.</h2></div><LumioDemo/></section>}
 <section className="le-shell le-documentation"><details className="le-archive"><summary><span><small>THE COMPLETE RECORD</small>Research, process & original material</span><ChevronDown size={24}/></summary><div className="notion-body" dangerouslySetInnerHTML={{__html:archive}}/></details><div className="le-credit"><p>Original project work through Awesomic. The source material credits intellectual-property ownership to Awesomic, Inc.</p><p>{interactive?'The interactive demo is a portfolio reconstruction using fictional data, not a live banking service.':'The original case is marked NDA. This presentation uses the material already included in the portfolio; further detail is available by request.'}</p></div></section>
 <section className="le-next"><a className="le-shell" href={`/cases/${next[0]}`}><span className="le-label">NEXT IN THE LUMIO SERIES</span><div><h2>{next[1]}</h2><ArrowRight size={42}/></div><p>Explore another part of the product.</p></a></section></main></LumioEditorialMotion><CaseFooter/></>;
}
