'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check} from 'lucide-react';
export function LumioAuth({onDone,onExplore}:{onDone:()=>void;onExplore:()=>void}){
 const [screen,setScreen]=useState('welcome');const [slide,setSlide]=useState(0);const [email,setEmail]=useState('');const [first,setFirst]=useState('');const [last,setLast]=useState('');const [pin,setPin]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const [provider,setProvider]=useState('');
 function go(value:string){setScreen(value);setError('');}
 return <div className="lx-auth" key={screen}>{screen!=='welcome'&&<button className="lw-action" onClick={()=>go('welcome')}><ArrowLeft size={18}/>Back to welcome</button>}
 {screen==='welcome'&&<><img className="lx-welcome-image" src="/images/lumio-phones.png" width="1080" height="1416" alt="Lumio personal and shared spending screens"/><h3>{['Personal & shared.','See it all in one place.','Control what you share.','Track balances together.'][slide]}</h3><p>{['Keep track of spending, balances, and savings between people.','Bring your accounts together without combining your money.','Keep individual purchases private while sharing everyday costs.','Understand contributions and plan your next shared milestone.'][slide]}</p><div className="lx-carousel" role="group" aria-label="Introduction slides">{[0,1,2,3].map(i=><button key={i} aria-label={`Introduction ${i+1}`} aria-pressed={slide===i} onClick={()=>setSlide(i)}><span/></button>)}</div><button className="ld-primary" onClick={()=>go('signup')}>Get started <ArrowRight size={16}/></button><button className="ld-text" onClick={()=>go('login')}>Log in</button><button className="ld-text" onClick={onExplore}>Explore sample app</button></>}
 {screen==='signup'&&<><h3>Create account</h3><p>Create a free account and start managing your money better, together.</p><form className="lw-form" onSubmit={e=>{e.preventDefault();if(email.toLowerCase()==='demo@lumio.example'){setError('This sample account already exists. Log in or use another sample email.');return;}go('verify');}}><label>Email<input required type="email" autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>First Name<input required maxLength={40} pattern=".*\S.*" value={first} onChange={e=>setFirst(e.target.value)}/></label><label>Surname<input required maxLength={40} pattern=".*\S.*" value={last} onChange={e=>setLast(e.target.value)}/></label><button className="ld-primary">Create Free Account</button></form><button className="lw-action" onClick={()=>{setProvider('Apple');go('provider');}}>Continue with Apple <ArrowRight size={16}/></button><button className="lw-action" onClick={()=>{setProvider('Google');go('provider');}}>Continue with Google <ArrowRight size={16}/></button><details className="lw-panel"><summary>Privacy & demo terms</summary><p>This reconstruction does not create a real Lumio account. Form entries remain in this tab and are cleared on restart.</p></details><button className="ld-text" onClick={()=>go('login')}>Already have an account? Log in</button></>}
 {screen==='provider'&&<><h3>Continue with {provider}</h3><p>Provider authentication is represented locally. No {provider} account is accessed.</p><button className="ld-primary" onClick={()=>{setEmail('demo@lumio.example');go('pin');}}>Continue as sample user</button><button className="ld-text" onClick={()=>go('signup')}>Cancel</button></>}
 {screen==='verify'&&<><h3>Verify your email</h3><p>Activation preview for {email}. No email has been sent.</p><button className="ld-primary" onClick={()=>go('pin')}>Preview email verification <Check size={16}/></button><button className="lw-action" onClick={()=>setError('A new verification preview is ready. No email was sent.')}>Resend verification</button><button className="lw-action" onClick={()=>go('signup')}>Change email address</button></>}
 {screen==='pin'&&<form className="lw-form" onSubmit={e=>{e.preventDefault();go('confirm');}}><h3>Create a passcode</h3><p>Choose five digits for this sample session. Do not use a real passcode.</p><label>Sample passcode<input type="password" inputMode="numeric" pattern="[0-9]{5}" maxLength={5} required autoComplete="off" value={pin} onChange={e=>setPin(e.target.value)}/></label><button className="ld-primary">Continue <ArrowRight size={16}/></button></form>}
 {screen==='confirm'&&<form className="lw-form" onSubmit={e=>{e.preventDefault();if(pin!==confirm){setError('Passcodes do not match. Try again.');setConfirm('');return;}go('ready');}}><h3>Confirm your passcode</h3><label>Confirm sample passcode<input type="password" inputMode="numeric" pattern="[0-9]{5}" maxLength={5} required autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="ld-primary">Confirm passcode</button><button type="button" className="lw-action" onClick={()=>go('pin')}>Choose another passcode</button></form>}
 {screen==='ready'&&<><div className="lx-check"><Check size={40}/></div><h3>Your space is ready.</h3><p>Explore shared spending first, or connect a sample bank now.</p><button className="ld-primary" onClick={onDone}>Connect a sample bank</button><button className="ld-text" onClick={onExplore}>Explore first</button></>}
 {screen==='login'&&<form className="lw-form" onSubmit={e=>{e.preventDefault();go('login-pin');}}><h3>Welcome back</h3><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="ld-primary">Continue</button><button type="button" className="ld-text" onClick={()=>go('signup')}>Create account</button></form>}
 {screen==='login-pin'&&<form className="lw-form" onSubmit={e=>{e.preventDefault();if(confirm!==(pin||'12345')){setError('Incorrect sample passcode. Try again or reset it.');return;}onExplore();}}><h3>Enter passcode</h3><p>Sample account: {email}. {pin?'Use the passcode created in this session.':'Demo passcode: 12345.'}</p><label>Login passcode<input type="password" required inputMode="numeric" pattern="[0-9]{5}" maxLength={5} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="ld-primary">Log in</button><button type="button" className="ld-text" onClick={()=>go('recovery')}>Forgot passcode?</button></form>}
 {screen==='recovery'&&<><h3>Reset passcode</h3><p>Preview account recovery for {email}. No reset link is sent.</p><button className="ld-primary" onClick={()=>{setConfirm('');go('pin');}}>Preview reset link</button><button className="ld-text" onClick={()=>go('login')}>Back to login</button></>}
 <p role="status" className="lw-status">{error}</p></div>;
}
