'use client';
import {useState} from 'react';
import {ArrowLeft, ArrowRight, Check, RotateCcw} from 'lucide-react';
import './lumio-demo.css';
import {LumioAuth} from './lumio-auth';
import {LumioWorkspace} from './lumio-workspace';

export function LumioDemo(){
 const [revision,setRevision]=useState(0);const [returnToSpace,setReturnToSpace]=useState(false);const [step,setStep]=useState(0);const [bank,setBank]=useState('');const [connected,setConnected]=useState(false);const [email,setEmail]=useState('');const [invited,setInvited]=useState(false);const [hidden,setHidden]=useState(false);
 const titles=['A little more together.','Choose your bank','Your accounts, your choice','Invite your partner','Your shared space'];
 function reset(){setRevision(v=>v+1);setReturnToSpace(false);setStep(0);setBank('');setConnected(false);setEmail('');setInvited(false);setHidden(false);}
 return <section className="lumio-demo" id="lumio-prototype" aria-labelledby="lumio-demo-title"><div className="ld-context"><span className="eyebrow">INTERACTIVE PRODUCT WALKTHROUGH</span><h2 id="lumio-demo-title">The first shared moment.</h2><p>Explore getting started, connecting a sample account, inviting a partner, and controlling what you share.</p><img src="/images/lumio-phones.png" alt="Original Lumio shared spending interface designs" width="1080" height="1416" loading="lazy"/><p className="ld-disclaimer">Reconstructed from surviving Lumio screenshots, component references, and the app screen map. Fictional balances and transactions; no banking connection or invitation is sent.</p><details className="lx-source-gallery"><summary>Original design references</summary><figure><img src="/notion/cfad2053-bd8b-4d58-88cf-f34790f44b32.webp" alt="Original Lumio shared spending screen with IOU controls" loading="lazy"/><figcaption>Shared spending and IOU controls</figcaption></figure><figure><img src="/notion/ed953546-0d85-4adc-b060-e0e3d9d43c42.webp" alt="Original Lumio transaction detail screen" loading="lazy"/><figcaption>Transaction categories, privacy and recurring costs</figcaption></figure><a className="text-link" href="/cases/lumio-design-system">Explore the design-system case</a></details></div><div className="ld-phone"><header><strong>lumio</strong><button onClick={reset} aria-label="Restart Lumio demo" title="Restart demo"><RotateCcw size={18}/></button></header><div className="ld-progress" aria-label={`Step ${step+1} of 5`}>{titles.map((t,i)=><span key={t} className={i<=step?'done':''}/>)}</div><div className="ld-screen" key={step}><div className="ld-back">{step>0&&step<4&&<button onClick={()=>{setStep(returnToSpace&&step===1?4:step===3&&!bank?1:step-1);}} aria-label="Previous step" title="Previous step"><ArrowLeft size={18}/></button>}<small>{step+1} / 5</small></div>{step>0&&step<4&&<h3>{titles[step]}</h3>}
 {step===0&&<LumioAuth key={revision} onDone={()=>setStep(1)} onExplore={()=>setStep(4)}/>}
 {step===1&&<><p>Select a sample bank. You can explore without connecting one.</p><fieldset><legend>Bank</legend>{['Monzo','Barclays','Starling'].map(b=><label className="ld-choice" key={b}><input type="radio" name="bank" value={b} checked={bank===b} onChange={()=>setBank(b)}/>{b}{bank===b&&<Check size={16}/>}</label>)}</fieldset><button className="ld-primary" disabled={!bank} onClick={()=>setStep(2)}>Continue <ArrowRight size={18}/></button><button className="ld-text" onClick={()=>{setConnected(false);setStep(returnToSpace?4:3);}}>Explore without a bank</button></>}
 {step===2&&<><p>{bank} · Sample current account ending 2048</p><div className="ld-balance"><small>Available balance</small><strong>£2,450.00</strong></div><p>You choose which transactions to share. This preview does not request banking credentials.</p><button className="ld-primary" onClick={()=>{setConnected(true);setStep(returnToSpace?4:3);}}>Use sample account <Check size={18}/></button><button className="ld-text" onClick={()=>setStep(1)}>Choose a different bank</button></>}
 {step===3&&<form onSubmit={e=>{e.preventDefault();setInvited(true);setStep(4);}}><p>Bring your partner into your shared space. You can also do this later.</p><label>Partner email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="partner@example.com"/></label><button className="ld-primary">Preview invitation <ArrowRight size={18}/></button><button className="ld-text" type="button" onClick={()=>setStep(4)}>I'll do this later</button></form>}

 </div><div hidden={step!==4} key={`workspace-${revision}`}><LumioWorkspace bank={bank} connected={connected} email={email} invited={invited} hidden={hidden} onPrivacy={()=>setHidden(v=>!v)} onConnect={()=>{setReturnToSpace(true);setStep(1);}} onDisconnect={()=>setConnected(false)} onInvite={value=>{setEmail(value);setInvited(true);}}/></div></div></section>;
}
