import './mango-case.css';
const root='/images/mango-case/';
const Screen=({name,alt}:{name:string;alt:string})=><img className="mg-screen" src={`${root}${name}.png`} alt={alt} width="750" height="1624" loading="lazy"/>;
export function MangoCase(){return <main id="main" className="mg-case">
<nav className="mg-nav" aria-label="Case navigation"><a href="/cases">← Marianna Gonchar</a><span>MANGO / PRODUCT DESIGN</span><a href="/mango-prototype/index.html">Play with the wallet ↗</a></nav>
<section className="mg-hero"><div className="mg-topline"><span>FINTECH, WITH A WARMER OUTLOOK.</span><span>CONCEPT REDESIGN / 2026</span></div><h1>A little crypto.<br/>A lot of <em>freedom.</em></h1><div className="mg-hero-bottom"><p>A familiar home for digital money.<br/>From the first hello to the next transaction.</p><a href="#experience">Explore the experience ↓</a></div><img className="mg-hero-board" src={`${root}mango-02.jpg`} alt="ManGo wallet interface on a warm yellow background" width="1600" height="1200"/></section>
<section className="mg-overview"><span className="mg-kicker">THE IDEA</span><h2>Make money moves<br/>feel <em>more human.</em></h2><div className="mg-overview-copy"><p>Crypto puts a lot of decisions in a small space. Which asset? How much? Where is it going? What happens next?</p><p>This ManGo exploration brings those decisions into a familiar mobile rhythm: a clear balance, focused actions, a review step, and a visible result.</p></div><dl><div><dt>Design scope</dt><dd>Mobile UX / UI<br/>Visual direction</dd></div><div><dt>Built experience</dt><dd>Connected flows<br/>Interactive prototype</dd></div><div><dt>Starting point</dt><dd>Existing ManGo<br/>onboarding designs</dd></div><div><dt>Project status</dt><dd>Concept redesign<br/>Simulated transactions</dd></div></dl></section>
<section className="mg-home" id="experience"><div className="mg-sticky"><span className="mg-kicker">01 / A CLEAR HOME</span><h2>Everything in place.<br/><em>You in control.</em></h2><p>The balance sets the hierarchy. Four everyday actions sit directly underneath it. Asset rows keep quantities and values together, with detail one tap away.</p><a className="mg-link" href="/mango-prototype/index.html">Try the wallet ↗</a></div><div className="mg-pair"><Screen name="wallet" alt="ManGo wallet balance, primary actions and four assets"/><Screen name="asset" alt="Bitcoin detail with balance, send, receive, swap and sell actions"/></div></section>
<section className="mg-statement"><span className="mg-kicker">THE DESIGN PRINCIPLE</span><p>Give the next move<br/><em>room to be obvious.</em></p><div>One decision at a time. One consistent visual language.</div></section>
<section className="mg-transactions"><div className="mg-chapter"><span className="mg-kicker">02 / MOVING MONEY</span><h2>Less guesswork.<br/><em>More intention.</em></h2><p>Each transaction follows a familiar sequence. Enter the details, review the amount and destination, then confirm. Completion updates both the balance and the activity trail.</p></div><div className="mg-three">{[['send','Send','A destination, an amount, and an explicit review.'],['swap','Swap','See the receiving asset and the estimated amount.'],['buy','Buy','Start with a familiar amount in dollars.']].map(([name,title,copy])=><figure key={name}><Screen name={name} alt={`${title} flow in the ManGo concept wallet`}/><figcaption><strong>{title}</strong><span>{copy}</span></figcaption></figure>)}</div><div className="mg-decisions"><article><span>01</span><h3>Review before action.</h3><p>The confirmation screen repeats the key details so a person can catch mistakes before committing.</p></article><article><span>02</span><h3>Recover in context.</h3><p>Invalid amounts, missing recipients, and insufficient demo funds keep people in the flow with a specific message.</p></article><article><span>03</span><h3>Show what changed.</h3><p>Successful actions update the wallet and create an activity entry with a readable detail view.</p></article></div></section>
<section className="mg-card-section"><div><span className="mg-kicker">03 / EVERYDAY FAMILIARITY</span><h2>Digital money.<br/><em>Everyday instincts.</em></h2><p>A card you can freeze. A transaction you can find. A balance you can hide. Familiar controls make the concept easier to explore.</p></div><div className="mg-pair"><Screen name="card" alt="ManGo demo card with freeze and details controls"/><Screen name="history" alt="Filterable transaction activity in the ManGo wallet"/></div></section>
<section className="mg-system"><span className="mg-kicker">04 / THE VISUAL LANGUAGE</span><h2>A serious foundation.<br/><em>A softer edge.</em></h2><div className="mg-type"><span>Aa</span><p>Strong hierarchy.<br/>Comfortable spacing.<br/>Warm, purposeful contrast.</p></div><div className="mg-swatches">{[['#10121A','Midnight'],['#FFD077','Mango'],['#F5F5FA','Soft white'],['#96DDC8','Mint']].map(([hex,name],i)=><div key={hex} style={{background:hex,color:i===0?'#fff':'#10121a'}}><span>{name}</span><strong>{hex}</strong></div>)}</div><p className="mg-system-note">Yellow identifies primary actions. Dark cards group related information. Rounded controls and restrained typography keep the interface approachable.</p></section>
<section className="mg-onboarding"><div className="mg-chapter"><span className="mg-kicker">05 / THE FIRST HELLO</span><h2>Begin with possibility.<br/><em>Build toward confidence.</em></h2><p>The original onboarding direction becomes the foundation for a warmer interface. Welcome, account setup, SMS, and PIN screens connect directly to the wallet.</p></div><div className="mg-three">{[['welcome','Welcome illustration and introduction'],['signup','Account creation form'],['pin','PIN creation with numeric keypad']].map(([name,alt])=><Screen key={name} name={name} alt={alt}/>)}</div></section>
<section className="mg-outcome"><span className="mg-kicker">WHAT THIS EXPLORATION DELIVERS</span><h2>A visual direction.<br/>A complete rhythm.<br/><em>A wallet you can try.</em></h2><div><p>The result is a connected prototype covering onboarding, assets, transfers, exchanges, buying, selling, activity, card controls, and profile settings.</p><p>This case demonstrates design and interaction intent. It does not claim a production launch, user research findings, or measured business results. The next validation step is to test asset selection, review comprehension, and recovery from common errors.</p></div><a className="mg-big-link" href="/mango-prototype/index.html">Make your next move. <span>↗</span></a></section>
<footer className="mg-footer"><a href="/cases">← More selected work</a><span>ManGo / Concept redesign</span><a href="mailto:marfantastik@gmail.com">Let’s build something thoughtful ↗</a></footer>
</main>}
