import cases from './data.json';
import previews from './archive-previews.json';
import {CaseHeader,CaseFooter} from './components';
import './archive-cards.css';

export const metadata={title:'All cases — Marianna Gonchar',description:'Product design, systems, websites and teaching by senior product designer Marianna Gonchar.'};
const groups=[['Product','Product thinking, in practice.'],['Systems','Foundations that connect the details.'],['Web','A wider range of digital craft.'],['Teaching','Sharing the practice.'],['Research','Questions still being explored.']];
type Preview = {src:string;alt:string;layout:string;second?:string;secondAlt?:string};
const images:Record<string,Preview>=previews;
const publicNames:Record<string,string>={"mango-bank":"Independent wallet concept","rainforest":"Home energy product","simcare":"AI counseling education","ascy":"Voice-first notes","causal-labs":"Weather intelligence","cloudbilling":"Billing platform","semaverse":"AI investment platform","lumio-couples":"Fintech product","lumio-activation":"Fintech activation","oasive":"Financial technology website","trucking":"Logistics platform","pearl":"Community platform","coinflix":"Entertainment platform","credit-decisioning":"Decisioning tool","lumio-design-system":"Fintech design system","lumio-visual-redesign":"Fintech product redesign","luxury-furniture":"Luxury commerce website","digitally":"Creative agency website","opus":"Property management website","cyberknife-miami":"Specialist healthcare website","delta10":"Public-sector learning platform","el-ticko":"Local services website","luxury-real-estate":"Real estate website","projector":"Design education","usability-research":"Usability research"};
const publicSummaries:Record<string,string>={"mango-bank":"A concept mobile wallet exploring onboarding, transfers, exchanges, activity and card controls.","rainforest":"Product design for a connected home-energy experience.","simcare":"Website UX/UI for an AI-enabled education product.","ascy":"Mobile UX/UI for a voice-first notes experience.","causal-labs":"Interface design and prototyping for a weather-intelligence product.","cloudbilling":"Website UX/UI for a complex billing product.","semaverse":"Product design for an AI platform handling complex information.","lumio-couples":"Product design for a shared-finance experience.","lumio-activation":"UX design for a fintech activation journey.","oasive":"Website design for a financial technology platform.","trucking":"Product design for a field-operations logistics platform.","pearl":"Design-system work for a community product.","coinflix":"Mobile product design for an entertainment platform.","credit-decisioning":"UX/UI for a complex decisioning tool.","lumio-design-system":"Design-system work for a fintech product.","lumio-visual-redesign":"Visual and product design for a fintech platform.","luxury-furniture":"Website UX/UI for a luxury commerce brand.","digitally":"Website design for a creative agency.","opus":"Website UX/UI for a property-management service.","cyberknife-miami":"Website UX/UI for a specialist healthcare service.","delta10":"Learning-platform UX/UI for public-sector education.","el-ticko":"Website UX/UI for a local services company.","luxury-real-estate":"Website redesign for a real-estate business.","projector":"Teaching and mentoring for mobile product design.","usability-research":"A work-in-progress usability research plan."};


export default function CaseArchive(){return <><CaseHeader/><main id="main" className="wrap archive"><div className="archive-intro"><div className="eyebrow">THE WORK / {String(cases.length).padStart(2,'0')} PROJECTS & PERSPECTIVES</div><h1>Different challenges.<br/>The same <span className="serif">curiosity.</span></h1><p>From product direction to the last interaction.<br/>Explore the work. Private projects are available with an access code.</p></div><nav className="archive-nav" aria-label="Case categories">{groups.map(([key])=><a key={key} href={`#${key.toLowerCase()}`}>{key} <span>{cases.filter(c=>c.category===key).length}</span></a>)}</nav>{groups.map(([key,title])=><section className="archive-group" id={key.toLowerCase()} key={key}><div className="section-heading"><h2>{key}</h2><span>{title}</span></div><div className="archive-card-grid">{cases.filter(c=>c.category===key).map(c=><a href={`/cases/${c.slug}`} className={`archive-card tone-${c.accent}`} key={c.slug}><div className={`archive-card-preview archive-preview-${images[c.slug]?.layout || 'research'}`}>
{images[c.slug]?<div className="archive-cover-art"><img src={images[c.slug].src} alt={images[c.slug].alt} loading="lazy" decoding="async"/>{images[c.slug].second && <img src={images[c.slug].second} alt={images[c.slug].secondAlt || `${publicNames[c.slug] || 'Project'} detail screen`} loading="lazy" decoding="async"/>}</div>:<div className="archive-research-preview"><span>RESEARCH PLAN</span><strong>The first<br/><i>five minutes.</i></strong><div><span>01 · Sign-up</span><span>02 · Setup</span><span>03 · Empty states</span></div><small>Moderated usability study · In progress</small></div>}
<span className="archive-card-access">{c.slug==='mango-bank'?'Public · Interactive preview':'NDA · Code required'}</span></div><div className="archive-card-copy"><div className="archive-card-meta"><span>{publicNames[c.slug] || 'Project'}</span><span aria-hidden="true">{String(cases.indexOf(c)+1).padStart(2,'0')}</span></div><h3>{c.title}</h3><p>{publicSummaries[c.slug] || c.summary}</p><div className="archive-card-action"><span>{c.slug==='mango-bank'?'Explore case study':'Unlock case study'}</span><span aria-hidden="true">↗</span></div></div></a>)}</div></section>)}</main><CaseFooter/></>}
