import cases from './data.json';
import previews from './archive-previews.json';
import {CaseHeader,CaseFooter} from './components';
import './archive-cards.css';

export const metadata={title:'All cases — Marianna Gonchar',description:'Product design, systems, websites and teaching by senior product designer Marianna Gonchar.'};
const groups=[['Product','Product thinking, in practice.'],['Systems','Foundations that connect the details.'],['Web','A wider range of digital craft.'],['Teaching','Sharing the practice.'],['Research','Questions still being explored.']];
type Preview = {src:string;alt:string;layout:string;second?:string;secondAlt?:string};
const images:Record<string,Preview>=previews;

export default function CaseArchive(){return <><CaseHeader/><main id="main" className="wrap archive"><div className="archive-intro"><div className="eyebrow">THE WORK / {String(cases.length).padStart(2,'0')} PROJECTS & PERSPECTIVES</div><h1>Different challenges.<br/>The same <span className="serif">curiosity.</span></h1><p>From product direction to the last interaction.<br/>Preview the work, then unlock a closer look.</p></div><nav className="archive-nav" aria-label="Case categories">{groups.map(([key])=><a key={key} href={`#${key.toLowerCase()}`}>{key} <span>{cases.filter(c=>c.category===key).length}</span></a>)}</nav>{groups.map(([key,title])=><section className="archive-group" id={key.toLowerCase()} key={key}><div className="section-heading"><h2>{key}</h2><span>{title}</span></div><div className="archive-card-grid">{cases.filter(c=>c.category===key).map(c=><a href={`/cases/${c.slug}`} className={`archive-card tone-${c.accent}`} key={c.slug}><div className={`archive-card-preview archive-preview-${images[c.slug]?.layout || 'research'}`}>
{images[c.slug]?<div className="archive-cover-art"><img src={images[c.slug].src} alt={images[c.slug].alt} loading="lazy" decoding="async"/>{images[c.slug].second && <img src={images[c.slug].second} alt={images[c.slug].secondAlt || `${c.name} detail screen`} loading="lazy" decoding="async"/>}</div>:<div className="archive-research-preview"><span>RESEARCH PLAN</span><strong>The first<br/><i>five minutes.</i></strong><div><span>01 · Sign-up</span><span>02 · Setup</span><span>03 · Empty states</span></div><small>Moderated usability study · In progress</small></div>}
<span className="archive-card-access">NDA · Code required</span></div><div className="archive-card-copy"><div className="archive-card-meta"><span>{c.name}</span><span aria-hidden="true">{String(cases.indexOf(c)+1).padStart(2,'0')}</span></div><h3>{c.title}</h3><p>{c.summary}</p><div className="archive-card-action"><span>Unlock case study</span><span aria-hidden="true">↗</span></div></div></a>)}</div></section>)}</main><CaseFooter/></>}
