import {CaseHeader,CaseFooter} from './components';
import {SimcareDemo} from './simcare-demo';
import './simcare-case.css';
const source='https://www.figma.com/design/vmAh6XN6flDftgJKjhE9zd/Simcare.ai?node-id=0-1';
const pages=[
 {key:'simulations',name:'Simulations',node:'189-2470',date:'12 August',image:'/images/simcare/simulations-1.png',heading:'Make the practice experience tangible.',body:'I led with a human conversation, then introduced the avatar library and a three-step practice flow. Custom scenarios, rubric-based feedback, supervisor tools, and comparison content give the product story depth beyond its opening promise. The page moves from what practice feels like to how a program can use it.'},
 {key:'fieldx',name:'FieldX',node:'185-2918',date:'11 August',image:'/images/simcare/fieldx-3.png',heading:'Explain the work behind field experience.',body:'I gave FieldX a dedicated product narrative around placements, hour tracking, evaluations, reporting, and program insights. Compact interface illustrations make these administrative tasks visible. Role-based content explains the experience for coordinators, supervisors, faculty, and students without creating a separate page for every audience.'},
 {key:'courses',name:'Course Catalog',node:'205-2079',date:'13 August',image:'/images/simcare/courses-5.png',heading:'Turn a catalog into a teaching workflow.',body:'I structured the page around browsing, selecting, and sharing a course. The design distinguishes focused scenarios from optional full sessions, then presents six course categories, clinical advisors, and detailed FAQs. This connects the course offering to how an instructor would introduce it in class.'},
 {key:'pricing',name:'Pricing',node:'186-4796',date:'11 August',image:'/images/simcare/courses-3.png',heading:'Make the options easy to compare.',body:'I organized the pricing concept into plan tiers, feature lists, a cost calculator, a comparison table, and FAQs. A dark featured plan and a colored enterprise option establish hierarchy. Some source copy remains provisional and references other products; this case presents the design structure rather than a finalized commercial offer.'},
 {key:'support',name:'Support',node:'185-2685',date:'11 August',image:'/images/simcare/support-1.png',heading:'Give getting started a clear home.',body:'I brought the student walkthrough, office hours, account manager support, contact options, and account setup into one support page. Human imagery accompanies the help channels, while numbered onboarding steps make the path into the platform explicit.'},
];
export function SimcareCase(){return <><CaseHeader/><main id="main" className="simcase"><section className="wrap simcase-intro"><a className="case-back" href="/cases">← All cases</a><span className="eyebrow">SIMCARE / WEBSITE DESIGN</span><h1>SimCare</h1><p className="simcase-deck">A connected website for counseling education, from first impression to first practice.</p><p className="simcase-summary">I designed the website across product storytelling, field experience, course discovery, pricing, and support. This case brings the latest desktop and mobile directions into an animated, navigable portfolio prototype.</p><dl className="case-details"><div><dt>My contribution</dt><dd>Website UX/UI · Product storytelling · Responsive layouts</dd></div><div><dt>Scope</dt><dd>5 connected pages · Desktop & mobile</dd></div><div><dt>Project material</dt><dd>Latest Figma iterations · 11–13 August</dd></div></dl><div className="simcase-links"><a className="pill-link" href="#website-preview">Explore all five pages ↓</a><a className="text-link" href={source} target="_blank" rel="noreferrer">View the Figma file ↗</a></div></section>
 <section className="simcase-preview-band" id="website-preview"><div className="wrap"><SimcareDemo/></div></section>
 <div className="wrap simcase-story"><section className="simcase-chapter"><div><span className="eyebrow">01 / THE CHALLENGE</span><h2>One product ecosystem.<br/>Several different questions.</h2></div><div><p>A prospective student wants to understand what practice feels like. A program needs to evaluate the tools, curriculum, cost, and rollout. Someone already using the product needs help getting started.</p><p>I separated those needs into five connected pages, using a shared visual language and navigation to make the website feel coherent as the content changes.</p></div></section>
 <section className="simcase-chapter"><div><span className="eyebrow">02 / DESIGN DEVELOPMENT</span><h2>Refine the structure.<br/>Then the details.</h2></div><div><p>The Figma workspace records a sequence of July and August iterations, from structural explorations to page-specific desktop and mobile layouts. For this portfolio version, I used the latest relevant frames on the right: the 11 August FieldX, Pricing, and Support designs, the 12 August Simulations design, and the 13 August Course Catalog design.</p><p>The progression includes product illustrations, audience-specific explanations, course content, support channels, and responsive refinements. The scope goes beyond a single homepage into a complete website journey.</p></div></section>
 {pages.map((p,i)=><section className={`simcase-page ${i%2?'simcase-reverse':''}`} key={p.key}><div><span className="eyebrow">{String(i+3).padStart(2,'0')} / {p.name.toUpperCase()}</span><h2>{p.heading}</h2><p>{p.body}</p><div className="simcase-links"><a className="text-link" href={`/simcare/${p.key}`} target="_blank" rel="noreferrer">Explore {p.name} ↗</a><a className="simcase-source-link" href={`https://www.figma.com/design/vmAh6XN6flDftgJKjhE9zd/Simcare.ai?node-id=${p.node}`} target="_blank" rel="noreferrer">{p.date} design ↗</a></div></div><a className={`simcase-page-image simcase-${p.key}`} href={`/simcare/${p.key}`} target="_blank" rel="noreferrer" aria-label={`Open animated ${p.name} page`}>{p.key==='pricing'?<div className="simcase-price-art">{[['Student','$79'],['Educator','$129'],['Program','$199'],['PRO','Custom']].map(([name,price])=><div key={name}><span>{name}</span><strong>{price}</strong><small>Design concept</small></div>)}</div>:<img src={p.image} alt={`${p.name} imagery from the SimCare design`} loading="lazy"/>}<span>{p.name} <span aria-hidden="true">↗</span></span></a></section>)}
 <section className="simcase-chapter"><div><span className="eyebrow">08 / VISUAL SYSTEM</span><h2>Human imagery.<br/>A consistent interface.</h2></div><div><p>I combined generous spacing, restrained typography, neutral surfaces, and rounded controls with imagery of counseling conversations and virtual clients. Product illustrations give abstract capabilities a concrete form, while repeated section patterns make long pages easier to scan.</p><p>The shared navigation, action styles, content hierarchy, and illustrated footer connect the pages. The mobile versions reorganize columns into a reading sequence while retaining the primary actions and product details.</p></div></section>
 <section className="simcase-chapter"><div><span className="eyebrow">09 / MOTION & INTERACTION</span><h2>Show the flow,<br/>not just the screen.</h2></div><div><p>The portfolio reconstruction adds scroll transitions, animated interface details, avatar and feature carousels, role switching, course previews, FAQs, and a working illustrative cost calculator. Each page is navigable, and the embedded preview lets visitors switch between all five designs.</p><p>Motion can be paused and respects reduced-motion preferences. Simulation and form flows use local preview states; they do not claim to provide the underlying AI, account, booking, or payment services. The coded reconstruction was created with AI assistance from my Figma designs.</p></div></section>
 <section className="simcase-result"><span className="eyebrow">THE DELIVERABLE</span><h2>A website story that continues<br/>beyond the homepage.</h2><p>The resulting design covers discovery, product evaluation, course exploration, pricing, and support through one connected experience. This case documents the design and its animated portfolio reconstruction, without attributing unverified launch, conversion, or learning outcomes to the work.</p><a className="pill-link" href="/simcare" target="_blank" rel="noreferrer">Open the animated website ↗</a></section><a className="next-case" href="/cases/causal-labs"><div><span className="eyebrow">NEXT / CAUSAL LABS</span><h2>Weather intelligence for aviation decisions.</h2></div><span aria-hidden="true">↗</span></a></div></main><CaseFooter/></>;}
