import './cases/causal-case.css';
import './portrait.css';
import './cases/simcare-case.css';
const Arrow = () => <span aria-hidden="true">↗</span>;
export default function Home() {
  return (
    <>
      <a className="skip-link" href="#main">Skip to content</a>
      <header className="site-header wrap">
        <a className="wordmark" href="#main" aria-label="Marianna Gonchar, home">Marianna Gonchar<span className="wordmark-dot">.</span></a>
        <nav aria-label="Main navigation"><a href="#cases">Cases</a><a href="#about">About</a><a href="/cv">CV <Arrow /></a><a className="nav-contact" href="mailto:marfantastik@gmail.com">Let’s talk <Arrow /></a></nav>
      </header>
      <main id="main">
        <section className="hero wrap" aria-labelledby="intro">
          <div className="eyebrow"><span className="status-dot"/>Independent thinking. Shared ambition.</div>
          <div className="portfolio-intro-with-photo"><h1 id="intro">Marianna Gonchar is a<br className="desktop-break"/> senior product designer<br className="desktop-break"/> making <span className="serif">complex</span> feel simple.</h1><img className="portfolio-portrait" src="/images/marianna-gonchar.jpeg" alt="Marianna Gonchar" width="1099" height="1415" fetchPriority="high"/></div>
          <div className="hero-bottom"><p>AI platforms. Everyday finances. Thoughtful digital experiences.<br/>From the first question to the details that make it work.</p><a className="text-link" href="#cases">Explore selected work <span aria-hidden="true">↓</span></a></div>
        </section>
        <section id="cases" className="work wrap" aria-labelledby="cases-title">
          <div className="section-heading"><h2 id="cases-title">Selected cases</h2><span>Strategy, systems & the details in between</span></div>
          <article className="project project-lumio">
            <a className="project-visual lumio-visual" href="/cases/lumio-couples" aria-label="Read Lumio couples finances case study"><span className="lumio-logotype">lumio<span>®</span></span><img src="/images/lumio-phones.png" alt="Lumio mobile app showing a couple’s shared spending and recurring expenses" width="1080" height="1416" loading="lazy"/><span className="visual-caption">A little more together.</span></a>
            <div className="project-copy"><div className="project-meta"><span>01 / LUMIO</span><span>FINTECH · MOBILE</span></div><h3>Shared money.<br/>Individual lives.</h3><p>Helping Lumio evolve from automatic savings to couples’ finances. End-to-end design, grounded in 32 user interviews and built around how people actually share money.</p><div className="role">Sole Designer · Research to release</div><a className="pill-link" href="/cases/lumio-couples">View case study <Arrow /></a></div>
          </article>
          <article className="project project-sema">
            <div className="project-copy"><div className="project-meta"><span>02 / SEMAVERSE</span><span>AI · B2B PLATFORM</span></div><h3>Clarity in a world<br/>of complex data.</h3><p>Redesigning an AI investment platform so people can navigate documents, understand system states, and work with confidence.</p><div className="role">Solo Product Designer · 2023–2026</div><a className="pill-link" href="/cases/semaverse">View case study <Arrow /></a></div>
            <a className="project-visual sema-visual" href="/cases/semaverse" aria-label="Read Semaverse case study"><span className="visual-label">SEMAVERSE / AI WORKSPACE</span><img src="/images/semaverse-vault.webp" alt="Semaverse AI Vault with document categories, processing progress, and an AI agent panel" width="2050" height="1460"/><span className="visual-footer">Complex workflows. Clear interactions.<span aria-hidden="true">↗</span></span></a>
          </article>
          <article className="project project-oasive">
            <a className="project-visual oasive-visual" href="/cases/oasive" aria-label="Read Oasive website case study"><span className="visual-label">OASIVE / WEBSITE DESIGN</span><img src="/images/oasive/live-og.webp" alt="Oasive website preview showing the product message and an animated research workspace" width="1200" height="630" loading="lazy"/><span className="visual-footer">Specialist finance. A clearer introduction.<span aria-hidden="true">↗</span></span></a>
            <div className="project-copy"><div className="project-meta"><span>03 / OASIVE</span><span>FINTECH · WEBSITE</span></div><h3>A complex product.<br/>A clear introduction.</h3><p>Designing and refining the website for an AI fixed-income platform—from the product story and visual hierarchy to motion and responsive detail.</p><div className="role">UX/UI design · Motion · Responsive refinement</div><a className="pill-link" href="/cases/oasive">View case study <Arrow /></a></div>
          </article>
          <article className="project project-simcare"><div className="project-copy"><div className="project-meta"><span>04 / SIMCARE</span><span>COUNSELING EDUCATION · WEBSITE</span></div><h3>A more human introduction<br/>to AI-powered practice.</h3><p>A connected website for simulations, field experience, course discovery, pricing, and support. Explore all five pages in an animated prototype.</p><div className="role">Website UX/UI · Product storytelling · Responsive design</div><a className="pill-link" href="/cases/simcare">View case study <Arrow /></a></div><a className="project-visual simcare-home-visual" href="/cases/simcare" aria-label="Read the SimCare website design case study"><img src="/images/simcare/simulations-1.png" alt="Counseling conversation from the SimCare website design" width="1360" height="800" loading="lazy"/><span>SIMCARE / FIVE CONNECTED PAGES<Arrow/></span></a></article>
          <article className="project project-coinflix"><div className="project-copy"><div className="project-meta"><span>05 / COINFLIX</span><span>ENTERTAINMENT · MOBILE</span></div><h3>Short-form stories.<br/>A bigger role for creators.</h3><p>Designing a mobile entertainment platform that brings content discovery, community, and creator monetization together, from early research to the full app experience.</p><div className="role">Senior Product Designer · Research · Mobile UX/UI</div><a className="pill-link" href="/cases/coinflix">View case study <Arrow /></a></div><a className="project-visual coinflix-visual" href="/cases/coinflix" aria-label="Read the Coinflix mobile product design case study"><span className="visual-label">COINFLIX / PRODUCT DESIGN</span><strong>coinflix<span aria-hidden="true">.</span></strong><div className="coinflix-topics"><span>Discover</span><span>Connect</span><span>Create</span></div><span className="visual-footer">Content. Community. Creator rewards.<Arrow /></span></a></article>
          <article className="project project-causal"><div className="project-copy"><div className="project-meta"><span>06 / CAUSAL LABS</span><span>WEATHER INTELLIGENCE · AVIATION</span></div><h3>Weather signals.<br/>Operational context.</h3><p>Connecting weather events, affected airports, and prediction timing in one map-based experience. Explore the design decisions through an animated, interactive prototype.</p><div className="role">Interface design · Interaction flows · Prototyping</div><a className="pill-link" href="/cases/causal-labs">View case study <Arrow /></a></div><a className="project-visual causal-preview" href="/cases/causal-labs" aria-label="Read the Causal Labs case study"><span className="visual-label">CAUSAL BRAIN / WEATHER INTELLIGENCE</span><img src="/images/causal/temperature.png" alt="Causal Labs continental weather map" width="1440" height="906" loading="lazy"/><span className="causal-preview-marker">ORD</span><span className="visual-footer">Overview. Airport detail. Forecast comparison.<Arrow/></span></a></article>
          <div className="more-work"><span>More explorations, different challenges.</span><a href="/cases">Browse the case archive <Arrow /></a></div>
        </section>
        <section id="about" className="about wrap" aria-labelledby="about-title"><div className="section-heading"><h2 id="about-title">A little about me</h2><span>Kyiv, Ukraine · Working internationally</span></div><div className="about-grid"><h3>Curious about people.<br/>Serious about <span className="serif">craft.</span></h3><div><p>I’m a Ukrainian product designer with 10+ years in the digital industry, working across startups, agencies, and complex products.</p><p>I connect research, product thinking, and hands-on design. Alongside my practice, I teach UX and mobile interface design at Projector Institute.</p><a className="text-link" href="/cv">More about my experience <Arrow /></a><a className="text-link design-room-link" href="/design-room">Visit my design room <Arrow /></a></div></div></section>
      </main>
      <footer className="footer"><div className="wrap"><div className="footer-top"><p>A new product. A complex challenge. Your next teammate.</p><a href="mailto:marfantastik@gmail.com">Let’s make it <span className="serif">matter.</span><Arrow /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Marianna Gonchar</span><div><a href="https://www.linkedin.com/in/marianna-gonchar-15933aa8/" target="_blank" rel="noreferrer">LinkedIn <Arrow /></a><a href="mailto:marfantastik@gmail.com">Email <Arrow /></a><a href="#main">Back to top ↑</a></div></div></div></footer>
    </>
  );
}
